// Mocks generated by Mockito 5.4.4 from annotations
// in xstream_gate_pass_app/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i16;

import 'package:cron/cron.dart' as _i12;
import 'package:dio/dio.dart' as _i7;
import 'package:flutter/material.dart' as _i15;
import 'package:internet_connection_checker/internet_connection_checker.dart'
    as _i11;
import 'package:logger/src/logger.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:stacked_services/stacked_services.dart' as _i13;
import 'package:xstream_gate_pass_app/core/enums/auth_portal.dart' as _i27;
import 'package:xstream_gate_pass_app/core/models/account/AuthenticateResultModel.dart'
    as _i9;
import 'package:xstream_gate_pass_app/core/models/account/ForgotPassword.dart'
    as _i29;
import 'package:xstream_gate_pass_app/core/models/account/GetCurrentLoginInformation.dart'
    as _i28;
import 'package:xstream_gate_pass_app/core/models/account/RegisterUser.dart'
    as _i37;
import 'package:xstream_gate_pass_app/core/models/account/ResetForgotPassword.dart'
    as _i38;
import 'package:xstream_gate_pass_app/core/models/account/TenantAvailableModel.dart'
    as _i36;
import 'package:xstream_gate_pass_app/core/models/account/UserCredential.dart'
    as _i34;
import 'package:xstream_gate_pass_app/core/models/background_job_que/background_job_Info.dart'
    as _i45;
import 'package:xstream_gate_pass_app/core/models/basefiles/containers/container_iso_types_model.dart'
    as _i19;
import 'package:xstream_gate_pass_app/core/models/basefiles/filestore/filestore.dart'
    as _i32;
import 'package:xstream_gate_pass_app/core/models/device/device_config.dart'
    as _i5;
import 'package:xstream_gate_pass_app/core/models/localization/localization_value.dart'
    as _i18;
import 'package:xstream_gate_pass_app/core/models/ops/checklists/check_list_find_template_model.dart'
    as _i4;
import 'package:xstream_gate_pass_app/core/models/ops/checklists/check_list_model.dart'
    as _i23;
import 'package:xstream_gate_pass_app/core/models/ops/checklists/check_list_resolve_type_output.dart'
    as _i26;
import 'package:xstream_gate_pass_app/core/models/ops/checklists/check_list_response_model.dart'
    as _i25;
import 'package:xstream_gate_pass_app/core/models/ops/incidents/incident_model.dart'
    as _i21;
import 'package:xstream_gate_pass_app/core/models/shared/api_response.dart'
    as _i8;
import 'package:xstream_gate_pass_app/core/models/shared/filter_params_model.dart'
    as _i24;
import 'package:xstream_gate_pass_app/core/services/api/api_manager.dart'
    as _i31;
import 'package:xstream_gate_pass_app/core/services/api/cms_api_manager.dart'
    as _i39;
import 'package:xstream_gate_pass_app/core/services/services/account/access_token_repo.dart'
    as _i33;
import 'package:xstream_gate_pass_app/core/services/services/account/auth_session_coordinator.dart'
    as _i42;
import 'package:xstream_gate_pass_app/core/services/services/account/authentication_service.dart'
    as _i35;
import 'package:xstream_gate_pass_app/core/services/services/account/cms_access_token_repo.dart'
    as _i40;
import 'package:xstream_gate_pass_app/core/services/services/account/cms_authentication_service.dart'
    as _i41;
import 'package:xstream_gate_pass_app/core/services/services/background/sync_manager_service.dart'
    as _i46;
import 'package:xstream_gate_pass_app/core/services/services/background/workqueue_manager.dart'
    as _i44;
import 'package:xstream_gate_pass_app/core/services/services/filestore/filestore_isolate_initializer.dart'
    as _i47;
import 'package:xstream_gate_pass_app/core/services/services/ops/checklists/check_list_service_service.dart'
    as _i22;
import 'package:xstream_gate_pass_app/core/services/services/ops/Incidents/incident_manager_service.dart'
    as _i20;
import 'package:xstream_gate_pass_app/core/services/shared/connection_service.dart'
    as _i43;
import 'package:xstream_gate_pass_app/core/services/shared/environment_service.dart'
    as _i30;
import 'package:xstream_gate_pass_app/core/services/shared/local_storage_service.dart'
    as _i6;
import 'package:xstream_gate_pass_app/core/services/shared/localization/localization_manager_service.dart'
    as _i17;
import 'package:xstream_gate_pass_app/services/iso_type_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContainerValidator_1 extends _i1.SmartFake
    implements _i3.ContainerValidator {
  _FakeContainerValidator_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCheckListFindTemplateModel_2 extends _i1.SmartFake
    implements _i4.CheckListFindTemplateModel {
  _FakeCheckListFindTemplateModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeviceConfig_3 extends _i1.SmartFake implements _i5.DeviceConfig {
  _FakeDeviceConfig_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocalStorageService_4 extends _i1.SmartFake
    implements _i6.LocalStorageService {
  _FakeLocalStorageService_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_5<T> extends _i1.SmartFake implements _i7.Response<T> {
  _FakeResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseResponse_6 extends _i1.SmartFake implements _i8.BaseResponse {
  _FakeBaseResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthenticateResultModel_7 extends _i1.SmartFake
    implements _i9.AuthenticateResultModel {
  _FakeAuthenticateResultModel_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamController_8<T> extends _i1.SmartFake
    implements _i10.StreamController<T> {
  _FakeStreamController_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternetConnectionChecker_9 extends _i1.SmartFake
    implements _i11.InternetConnectionChecker {
  _FakeInternetConnectionChecker_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCron_10 extends _i1.SmartFake implements _i12.Cron {
  _FakeCron_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeScheduledTask_11 extends _i1.SmartFake
    implements _i12.ScheduledTask {
  _FakeScheduledTask_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i13.NavigationService {
  @override
  String get previousRoute => (super.noSuchMethod(
        Invocation.getter(#previousRoute),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
      ) as String);

  @override
  String get currentRoute => (super.noSuchMethod(
        Invocation.getter(#currentRoute),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
      ) as String);

  @override
  _i15.GlobalKey<_i15.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(
        Invocation.method(
          #nestedNavigationKey,
          [index],
        ),
        returnValueForMissingStub: null,
      ) as _i15.GlobalKey<_i15.NavigatorState>?);

  @override
  void config({
    bool? enableLog,
    bool? defaultPopGesture,
    bool? defaultOpaqueRoute,
    Duration? defaultDurationTransition,
    bool? defaultGlobalState,
    _i13.Transition? defaultTransitionStyle,
    String? defaultTransition,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #config,
          [],
          {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransitionStyle: defaultTransitionStyle,
            #defaultTransition: defaultTransition,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<T?>? navigateWithTransition<T>(
    _i15.Widget? page, {
    bool? opaque,
    String? transition = r'',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i15.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i13.Transition? transitionClass,
    _i13.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i10.Future<T?>?);

  @override
  _i10.Future<T?>? replaceWithTransition<T>(
    _i15.Widget? page, {
    bool? opaque,
    String? transition = r'',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i15.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i13.Transition? transitionClass,
    _i13.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i10.Future<T?>?);

  @override
  bool back<T>({
    dynamic result,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {
            #result: result,
            #id: id,
          },
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void popUntil(
    _i15.RoutePredicate? predicate, {
    int? id,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntil,
          [predicate],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void popRepeated(int? popTimes) => super.noSuchMethod(
        Invocation.method(
          #popRepeated,
          [popTimes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<T?>? navigateTo<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i15.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i10.Future<T?>?);

  @override
  _i10.Future<T?>? navigateToView<T>(
    _i15.Widget? view, {
    dynamic arguments,
    int? id,
    bool? opaque,
    _i15.Curve? curve,
    Duration? duration,
    bool? fullscreenDialog = false,
    bool? popGesture,
    bool? preventDuplicates = true,
    _i13.Transition? transition,
    _i13.Transition? transitionStyle,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToView,
          [view],
          {
            #arguments: arguments,
            #id: id,
            #opaque: opaque,
            #curve: curve,
            #duration: duration,
            #fullscreenDialog: fullscreenDialog,
            #popGesture: popGesture,
            #preventDuplicates: preventDuplicates,
            #transition: transition,
            #transitionStyle: transitionStyle,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i10.Future<T?>?);

  @override
  _i10.Future<T?>? replaceWith<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i15.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWith,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i10.Future<T?>?);

  @override
  _i10.Future<T?>? clearStackAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i10.Future<T?>?);

  @override
  _i10.Future<T?>? clearStackAndShowView<T>(
    _i15.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i10.Future<T?>?);

  @override
  _i10.Future<T?>? clearTillFirstAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i10.Future<T?>?);

  @override
  _i10.Future<T?>? clearTillFirstAndShowView<T>(
    _i15.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i10.Future<T?>?);

  @override
  _i10.Future<T?>? pushNamedAndRemoveUntil<T>(
    String? routeName, {
    _i15.RoutePredicate? predicate,
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamedAndRemoveUntil,
          [routeName],
          {
            #predicate: predicate,
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i10.Future<T?>?);
}

/// A class which mocks [BottomSheetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBottomSheetService extends _i1.Mock
    implements _i13.BottomSheetService {
  @override
  void setCustomSheetBuilders(Map<dynamic, _i13.SheetBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #setCustomSheetBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<_i13.SheetResponse<dynamic>?> showBottomSheet({
    required String? title,
    String? description,
    String? confirmButtonTitle = r'Ok',
    String? cancelButtonTitle,
    bool? enableDrag = true,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
    double? elevation = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [],
          {
            #title: title,
            #description: description,
            #confirmButtonTitle: confirmButtonTitle,
            #cancelButtonTitle: cancelButtonTitle,
            #enableDrag: enableDrag,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
            #elevation: elevation,
          },
        ),
        returnValue: _i10.Future<_i13.SheetResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i10.Future<_i13.SheetResponse<dynamic>?>.value(),
      ) as _i10.Future<_i13.SheetResponse<dynamic>?>);

  @override
  _i10.Future<_i13.SheetResponse<T>?> showCustomSheet<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i16.Color? barrierColor = const _i16.Color(2315255808),
    double? elevation = 1.0,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    String? barrierLabel = r'',
    dynamic customData,
    R? data,
    bool? enableDrag = true,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomSheet,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #elevation: elevation,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #barrierLabel: barrierLabel,
            #customData: customData,
            #data: data,
            #enableDrag: enableDrag,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i10.Future<_i13.SheetResponse<T>?>.value(),
        returnValueForMissingStub: _i10.Future<_i13.SheetResponse<T>?>.value(),
      ) as _i10.Future<_i13.SheetResponse<T>?>);

  @override
  void completeSheet(_i13.SheetResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeSheet,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i13.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i13.DialogBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i15.Widget Function(
      _i15.BuildContext,
      _i13.DialogRequest<dynamic>,
      dynamic Function(_i13.DialogResponse<dynamic>),
    )? builder,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilder,
          [],
          {
            #variant: variant,
            #builder: builder,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<_i13.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i16.Color? cancelTitleColor,
    String? buttonTitle = r'Ok',
    _i16.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i15.RouteSettings? routeSettings,
    _i15.GlobalKey<_i15.NavigatorState>? navigatorKey,
    _i13.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #buttonTitle: buttonTitle,
            #buttonTitleColor: buttonTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i10.Future<_i13.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i10.Future<_i13.DialogResponse<dynamic>?>.value(),
      ) as _i10.Future<_i13.DialogResponse<dynamic>?>);

  @override
  _i10.Future<_i13.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i16.Color? barrierColor = const _i16.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = r'',
    bool? useSafeArea = true,
    _i15.RouteSettings? routeSettings,
    _i15.GlobalKey<_i15.NavigatorState>? navigatorKey,
    _i15.RouteTransitionsBuilder? transitionBuilder,
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomDialog,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #barrierLabel: barrierLabel,
            #useSafeArea: useSafeArea,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #transitionBuilder: transitionBuilder,
            #customData: customData,
            #data: data,
          },
        ),
        returnValue: _i10.Future<_i13.DialogResponse<T>?>.value(),
        returnValueForMissingStub: _i10.Future<_i13.DialogResponse<T>?>.value(),
      ) as _i10.Future<_i13.DialogResponse<T>?>);

  @override
  _i10.Future<_i13.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = r'Cancel',
    _i16.Color? cancelTitleColor,
    String? confirmationTitle = r'Ok',
    _i16.Color? confirmationTitleColor,
    bool? barrierDismissible = false,
    _i15.RouteSettings? routeSettings,
    _i13.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showConfirmationDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #confirmationTitle: confirmationTitle,
            #confirmationTitleColor: confirmationTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i10.Future<_i13.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i10.Future<_i13.DialogResponse<dynamic>?>.value(),
      ) as _i10.Future<_i13.DialogResponse<dynamic>?>);

  @override
  void completeDialog(_i13.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeDialog,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LocalizationManagerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalizationManagerService extends _i1.Mock
    implements _i17.LocalizationManagerService {
  @override
  _i2.Logger get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
      ) as _i2.Logger);

  @override
  set userId(int? _userId) => super.noSuchMethod(
        Invocation.setter(
          #userId,
          _userId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i18.LocalizationValue> get localizationValues => (super.noSuchMethod(
        Invocation.getter(#localizationValues),
        returnValue: <_i18.LocalizationValue>[],
        returnValueForMissingStub: <_i18.LocalizationValue>[],
      ) as List<_i18.LocalizationValue>);

  @override
  void setTableRef() => super.noSuchMethod(
        Invocation.method(
          #setTableRef,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> insert(_i18.LocalizationValue? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [entity],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> update(_i18.LocalizationValue? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [entity],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> upsertMany(List<_i18.LocalizationValue>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertMany,
          [entities],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i18.LocalizationValue?> findByKey(String? key) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByKey,
          [key],
        ),
        returnValue: _i10.Future<_i18.LocalizationValue?>.value(),
        returnValueForMissingStub: _i10.Future<_i18.LocalizationValue?>.value(),
      ) as _i10.Future<_i18.LocalizationValue?>);

  @override
  _i10.Future<void> delete(_i18.LocalizationValue? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [entity],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteMany(List<_i18.LocalizationValue>? entities) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMany,
          [entities],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> clearTableTripstop() => (super.noSuchMethod(
        Invocation.method(
          #clearTableTripstop,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i18.LocalizationValue>> getAllLocal(String? searchArg) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllLocal,
          [searchArg],
        ),
        returnValue: _i10.Future<List<_i18.LocalizationValue>>.value(
            <_i18.LocalizationValue>[]),
        returnValueForMissingStub:
            _i10.Future<List<_i18.LocalizationValue>>.value(
                <_i18.LocalizationValue>[]),
      ) as _i10.Future<List<_i18.LocalizationValue>>);

  @override
  _i10.Future<List<_i18.LocalizationValue>> getLocalizeValues() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalizeValues,
          [],
        ),
        returnValue: _i10.Future<List<_i18.LocalizationValue>>.value(
            <_i18.LocalizationValue>[]),
        returnValueForMissingStub:
            _i10.Future<List<_i18.LocalizationValue>>.value(
                <_i18.LocalizationValue>[]),
      ) as _i10.Future<List<_i18.LocalizationValue>>);

  @override
  bool hasPermission(String? key) => (super.noSuchMethod(
        Invocation.method(
          #hasPermission,
          [key],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String localize(String? key) => (super.noSuchMethod(
        Invocation.method(
          #localize,
          [key],
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #localize,
            [key],
          ),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #localize,
            [key],
          ),
        ),
      ) as String);
}

/// A class which mocks [IsoTypeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsoTypeService extends _i1.Mock implements _i3.IsoTypeService {
  @override
  Map<String, _i19.IsoType> get isoTypesMap => (super.noSuchMethod(
        Invocation.getter(#isoTypesMap),
        returnValue: <String, _i19.IsoType>{},
        returnValueForMissingStub: <String, _i19.IsoType>{},
      ) as Map<String, _i19.IsoType>);

  @override
  set isoTypesMap(Map<String, _i19.IsoType>? _isoTypesMap) =>
      super.noSuchMethod(
        Invocation.setter(
          #isoTypesMap,
          _isoTypesMap,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ContainerValidator get validator => (super.noSuchMethod(
        Invocation.getter(#validator),
        returnValue: _FakeContainerValidator_1(
          this,
          Invocation.getter(#validator),
        ),
        returnValueForMissingStub: _FakeContainerValidator_1(
          this,
          Invocation.getter(#validator),
        ),
      ) as _i3.ContainerValidator);

  @override
  set validator(_i3.ContainerValidator? _validator) => super.noSuchMethod(
        Invocation.setter(
          #validator,
          _validator,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i19.IsoType> get isoTypes => (super.noSuchMethod(
        Invocation.getter(#isoTypes),
        returnValue: <_i19.IsoType>[],
        returnValueForMissingStub: <_i19.IsoType>[],
      ) as List<_i19.IsoType>);

  @override
  List<_i19.IsoType> get getAllIsoTypes => (super.noSuchMethod(
        Invocation.getter(#getAllIsoTypes),
        returnValue: <_i19.IsoType>[],
        returnValueForMissingStub: <_i19.IsoType>[],
      ) as List<_i19.IsoType>);

  @override
  _i10.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  int iso6346CheckDigit(String? csc) => (super.noSuchMethod(
        Invocation.method(
          #iso6346CheckDigit,
          [csc],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i10.Future<void> loadIsoTypes() => (super.noSuchMethod(
        Invocation.method(
          #loadIsoTypes,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i19.IsoType? findByCode(String? code) => (super.noSuchMethod(
        Invocation.method(
          #findByCode,
          [code],
        ),
        returnValueForMissingStub: null,
      ) as _i19.IsoType?);

  @override
  String? getDescriptionForCode(String? code) => (super.noSuchMethod(
        Invocation.method(
          #getDescriptionForCode,
          [code],
        ),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  List<_i19.IsoType> findBySize(String? size) => (super.noSuchMethod(
        Invocation.method(
          #findBySize,
          [size],
        ),
        returnValue: <_i19.IsoType>[],
        returnValueForMissingStub: <_i19.IsoType>[],
      ) as List<_i19.IsoType>);

  @override
  List<_i19.IsoType> findByType(String? type) => (super.noSuchMethod(
        Invocation.method(
          #findByType,
          [type],
        ),
        returnValue: <_i19.IsoType>[],
        returnValueForMissingStub: <_i19.IsoType>[],
      ) as List<_i19.IsoType>);

  @override
  Set<String> getAllCodes() => (super.noSuchMethod(
        Invocation.method(
          #getAllCodes,
          [],
        ),
        returnValue: <String>{},
        returnValueForMissingStub: <String>{},
      ) as Set<String>);
}

/// A class which mocks [IncidentManagerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIncidentManagerService extends _i1.Mock
    implements _i20.IncidentManagerService {
  @override
  _i2.Logger get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
      ) as _i2.Logger);

  @override
  _i10.Future<_i21.Incident?> createIncident(dynamic entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #createIncident,
          [entity],
        ),
        returnValue: _i10.Future<_i21.Incident?>.value(),
        returnValueForMissingStub: _i10.Future<_i21.Incident?>.value(),
      ) as _i10.Future<_i21.Incident?>);

  @override
  _i10.Future<void> logManualInput(
    String? gatePassId,
    String? fieldType,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logManualInput,
          [
            gatePassId,
            fieldType,
            value,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> logTrailerOverride(
    String? gatePassId,
    String? trailerType,
    String? expectedValue,
    String? enteredValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logTrailerOverride,
          [
            gatePassId,
            trailerType,
            expectedValue,
            enteredValue,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [CheckListServiceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckListServiceService extends _i1.Mock
    implements _i22.CheckListServiceService {
  @override
  _i2.Logger get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
      ) as _i2.Logger);

  @override
  _i10.Future<_i23.CheckList?> getEmptyChecklistForGatePass(
          _i24.FilterParams? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEmptyChecklistForGatePass,
          [entity],
        ),
        returnValue: _i10.Future<_i23.CheckList?>.value(),
        returnValueForMissingStub: _i10.Future<_i23.CheckList?>.value(),
      ) as _i10.Future<_i23.CheckList?>);

  @override
  _i10.Future<_i23.CheckList?> submitResponses(
          _i25.CheckListResponseModel? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitResponses,
          [entity],
        ),
        returnValue: _i10.Future<_i23.CheckList?>.value(),
        returnValueForMissingStub: _i10.Future<_i23.CheckList?>.value(),
      ) as _i10.Future<_i23.CheckList?>);

  @override
  _i10.Future<_i4.CheckListFindTemplateModel> findChecklistTemplate(
          _i24.FilterParams? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #findChecklistTemplate,
          [entity],
        ),
        returnValue: _i10.Future<_i4.CheckListFindTemplateModel>.value(
            _FakeCheckListFindTemplateModel_2(
          this,
          Invocation.method(
            #findChecklistTemplate,
            [entity],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i4.CheckListFindTemplateModel>.value(
                _FakeCheckListFindTemplateModel_2(
          this,
          Invocation.method(
            #findChecklistTemplate,
            [entity],
          ),
        )),
      ) as _i10.Future<_i4.CheckListFindTemplateModel>);

  @override
  _i10.Future<_i26.CheckListResolveTypeOutput?> resolveChecklistType(
          String? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveChecklistType,
          [status],
        ),
        returnValue: _i10.Future<_i26.CheckListResolveTypeOutput?>.value(),
        returnValueForMissingStub:
            _i10.Future<_i26.CheckListResolveTypeOutput?>.value(),
      ) as _i10.Future<_i26.CheckListResolveTypeOutput?>);
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i6.LocalStorageService {
  @override
  _i2.Logger get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
      ) as _i2.Logger);

  @override
  _i5.DeviceConfig get getDeviceConfig => (super.noSuchMethod(
        Invocation.getter(#getDeviceConfig),
        returnValue: _FakeDeviceConfig_3(
          this,
          Invocation.getter(#getDeviceConfig),
        ),
        returnValueForMissingStub: _FakeDeviceConfig_3(
          this,
          Invocation.getter(#getDeviceConfig),
        ),
      ) as _i5.DeviceConfig);

  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasDisclosedBackgroundPermission => (super.noSuchMethod(
        Invocation.getter(#hasDisclosedBackgroundPermission),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i10.Future<_i6.LocalStorageService> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i10.Future<_i6.LocalStorageService>.value(
            _FakeLocalStorageService_4(
          this,
          Invocation.method(
            #init,
            [],
          ),
        )),
        returnValueForMissingStub: _i10.Future<_i6.LocalStorageService>.value(
            _FakeLocalStorageService_4(
          this,
          Invocation.method(
            #init,
            [],
          ),
        )),
      ) as _i10.Future<_i6.LocalStorageService>);

  @override
  void setDeviceConfig(_i5.DeviceConfig? deviceConfig) => super.noSuchMethod(
        Invocation.method(
          #setDeviceConfig,
          [deviceConfig],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearTenantId() => super.noSuchMethod(
        Invocation.method(
          #clearTenantId,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearTenantIdForPortal(_i27.AuthPortal? portal) => super.noSuchMethod(
        Invocation.method(
          #clearTenantIdForPortal,
          [portal],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTenantId(int? value) => super.noSuchMethod(
        Invocation.method(
          #setTenantId,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTenantIdForPortal(
    _i27.AuthPortal? portal,
    int? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setTenantIdForPortal,
          [
            portal,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int? getTenantIdForPortal(_i27.AuthPortal? portal) => (super.noSuchMethod(
        Invocation.method(
          #getTenantIdForPortal,
          [portal],
        ),
        returnValueForMissingStub: null,
      ) as int?);

  @override
  _i9.AuthenticateResultModel? getAuthTokenForPortal(_i27.AuthPortal? portal) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuthTokenForPortal,
          [portal],
        ),
        returnValueForMissingStub: null,
      ) as _i9.AuthenticateResultModel?);

  @override
  void setAuthToken(_i9.AuthenticateResultModel? authToken) =>
      super.noSuchMethod(
        Invocation.method(
          #setAuthToken,
          [authToken],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAuthTokenForPortal(
    _i27.AuthPortal? portal,
    _i9.AuthenticateResultModel? authToken,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setAuthTokenForPortal,
          [
            portal,
            authToken,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAuthToken() => super.noSuchMethod(
        Invocation.method(
          #clearAuthToken,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAuthTokenForPortal(_i27.AuthPortal? portal) => super.noSuchMethod(
        Invocation.method(
          #clearAuthTokenForPortal,
          [portal],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logout() => super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logoutPortal(_i27.AuthPortal? portal) => super.noSuchMethod(
        Invocation.method(
          #logoutPortal,
          [portal],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logoutAllPortals() => super.noSuchMethod(
        Invocation.method(
          #logoutAllPortals,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearForgotPassword() => super.noSuchMethod(
        Invocation.method(
          #clearForgotPassword,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i28.CurrentLoginInformation? getUserLoginInfoForPortal(
          _i27.AuthPortal? portal) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserLoginInfoForPortal,
          [portal],
        ),
        returnValueForMissingStub: null,
      ) as _i28.CurrentLoginInformation?);

  @override
  void setUserLoginInfo(_i28.CurrentLoginInformation? userLoginInfo) =>
      super.noSuchMethod(
        Invocation.method(
          #setUserLoginInfo,
          [userLoginInfo],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUserLoginInfoForPortal(
    _i27.AuthPortal? portal,
    _i28.CurrentLoginInformation? userLoginInfo,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setUserLoginInfoForPortal,
          [
            portal,
            userLoginInfo,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isLoggedInForPortal(_i27.AuthPortal? portal) => (super.noSuchMethod(
        Invocation.method(
          #isLoggedInForPortal,
          [portal],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void saveIsLoggedIn(bool? value) => super.noSuchMethod(
        Invocation.method(
          #saveIsLoggedIn,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void saveIsLoggedInForPortal(
    _i27.AuthPortal? portal,
    bool? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #saveIsLoggedInForPortal,
          [
            portal,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLastSessionPortal(_i27.AuthPortal? portal) => super.noSuchMethod(
        Invocation.method(
          #setLastSessionPortal,
          [portal],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getTenantCodeForPortal(_i27.AuthPortal? portal) => (super.noSuchMethod(
        Invocation.method(
          #getTenantCodeForPortal,
          [portal],
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getTenantCodeForPortal,
            [portal],
          ),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getTenantCodeForPortal,
            [portal],
          ),
        ),
      ) as String);

  @override
  void setTenantCodeForPortal(
    _i27.AuthPortal? portal,
    String? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setTenantCodeForPortal,
          [
            portal,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void saveHasDisclosedBackgroundPermission(bool? value) => super.noSuchMethod(
        Invocation.method(
          #saveHasDisclosedBackgroundPermission,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getStringByKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getStringByKey,
          [key],
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getStringByKey,
            [key],
          ),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getStringByKey,
            [key],
          ),
        ),
      ) as String);

  @override
  void setStringByKey(
    String? key,
    String? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setStringByKey,
          [
            key,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> getRecentSearches() => (super.noSuchMethod(
        Invocation.method(
          #getRecentSearches,
          [],
        ),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  void clearRecentSearches() => super.noSuchMethod(
        Invocation.method(
          #clearRecentSearches,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void saveToRecentSearches(String? searchText) => super.noSuchMethod(
        Invocation.method(
          #saveToRecentSearches,
          [searchText],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int? getNavTabIndex(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getNavTabIndex,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as int?);

  @override
  void setNavTabIndex(
    String? key,
    int? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setNavTabIndex,
          [
            key,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearNavTabIndex(String? key) => super.noSuchMethod(
        Invocation.method(
          #clearNavTabIndex,
          [key],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setForgotPassword(_i29.ForgotPassword? forgotPasswordReponse) =>
      super.noSuchMethod(
        Invocation.method(
          #setForgotPassword,
          [forgotPasswordReponse],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [EnvironmentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnvironmentService extends _i1.Mock
    implements _i30.EnvironmentService {
  @override
  _i2.Logger get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
      ) as _i2.Logger);

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  set baseUrl(String? _baseUrl) => super.noSuchMethod(
        Invocation.setter(
          #baseUrl,
          _baseUrl,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void setBasics() => super.noSuchMethod(
        Invocation.method(
          #setBasics,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getBaseUrl(_i27.AuthPortal? portal) => (super.noSuchMethod(
        Invocation.method(
          #getBaseUrl,
          [portal],
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getBaseUrl,
            [portal],
          ),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getBaseUrl,
            [portal],
          ),
        ),
      ) as String);

  @override
  String getHostName(_i27.AuthPortal? portal) => (super.noSuchMethod(
        Invocation.method(
          #getHostName,
          [portal],
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getHostName,
            [portal],
          ),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getHostName,
            [portal],
          ),
        ),
      ) as String);

  @override
  String getValue(
    String? key, {
    bool? verbose = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getValue,
          [key],
          {#verbose: verbose},
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getValue,
            [key],
            {#verbose: verbose},
          ),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getValue,
            [key],
            {#verbose: verbose},
          ),
        ),
      ) as String);
}

/// A class which mocks [ApiManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiManager extends _i1.Mock implements _i31.ApiManager {
  @override
  _i2.Logger get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
      ) as _i2.Logger);

  @override
  _i10.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  dynamic handelError(_i7.DioException? dioError) => super.noSuchMethod(
        Invocation.method(
          #handelError,
          [dioError],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<_i7.Response<dynamic>> retryInternal(
          _i7.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #retryInternal,
          [requestOptions],
        ),
        returnValue:
            _i10.Future<_i7.Response<dynamic>>.value(_FakeResponse_5<dynamic>(
          this,
          Invocation.method(
            #retryInternal,
            [requestOptions],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i7.Response<dynamic>>.value(_FakeResponse_5<dynamic>(
          this,
          Invocation.method(
            #retryInternal,
            [requestOptions],
          ),
        )),
      ) as _i10.Future<_i7.Response<dynamic>>);

  @override
  _i10.Future<dynamic> get(
    String? uri, {
    Map<String, dynamic>? queryParameters,
    _i7.Options? options,
    _i7.CancelToken? cancelToken,
    _i7.ProgressCallback? onReceiveProgress,
    bool? showLoader = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [uri],
          {
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
            #showLoader: showLoader,
          },
        ),
        returnValue: _i10.Future<dynamic>.value(),
        returnValueForMissingStub: _i10.Future<dynamic>.value(),
      ) as _i10.Future<dynamic>);

  @override
  _i10.Future<dynamic> uploadLoadImages(_i32.FileStore? fileStore) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadLoadImages,
          [fileStore],
        ),
        returnValue: _i10.Future<dynamic>.value(),
        returnValueForMissingStub: _i10.Future<dynamic>.value(),
      ) as _i10.Future<dynamic>);

  @override
  _i10.Future<dynamic> postWithFile({
    required String? uri,
    required String? filePath,
    required String? fileName,
    required Map<String, dynamic>? modelData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postWithFile,
          [],
          {
            #uri: uri,
            #filePath: filePath,
            #fileName: fileName,
            #modelData: modelData,
          },
        ),
        returnValue: _i10.Future<dynamic>.value(),
        returnValueForMissingStub: _i10.Future<dynamic>.value(),
      ) as _i10.Future<dynamic>);

  @override
  _i10.Future<dynamic> post(
    String? uri, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i7.Options? options,
    _i7.CancelToken? cancelToken,
    _i7.ProgressCallback? onSendProgress,
    _i7.ProgressCallback? onReceiveProgress,
    bool? showLoader = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [uri],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
            #showLoader: showLoader,
          },
        ),
        returnValue: _i10.Future<dynamic>.value(),
        returnValueForMissingStub: _i10.Future<dynamic>.value(),
      ) as _i10.Future<dynamic>);

  @override
  _i10.Future<dynamic> put(
    String? uri, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i7.Options? options,
    _i7.CancelToken? cancelToken,
    _i7.ProgressCallback? onSendProgress,
    _i7.ProgressCallback? onReceiveProgress,
    bool? showLoader = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [uri],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
            #showLoader: showLoader,
          },
        ),
        returnValue: _i10.Future<dynamic>.value(),
        returnValueForMissingStub: _i10.Future<dynamic>.value(),
      ) as _i10.Future<dynamic>);

  @override
  _i10.Future<_i7.Response<dynamic>> request(
    String? uri, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i7.Options? options,
    _i7.CancelToken? cancelToken,
    _i7.ProgressCallback? onSendProgress,
    _i7.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [uri],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i10.Future<_i7.Response<dynamic>>.value(_FakeResponse_5<dynamic>(
          this,
          Invocation.method(
            #request,
            [uri],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i7.Response<dynamic>>.value(_FakeResponse_5<dynamic>(
          this,
          Invocation.method(
            #request,
            [uri],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i10.Future<_i7.Response<dynamic>>);
}

/// A class which mocks [AccessTokenRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccessTokenRepo extends _i1.Mock implements _i33.AccessTokenRepo {
  @override
  _i2.Logger get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
      ) as _i2.Logger);

  @override
  _i10.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i9.AuthenticateResultModel?>
      getAccessTokenFromStorageOrRefresh() => (super.noSuchMethod(
            Invocation.method(
              #getAccessTokenFromStorageOrRefresh,
              [],
            ),
            returnValue: _i10.Future<_i9.AuthenticateResultModel?>.value(),
            returnValueForMissingStub:
                _i10.Future<_i9.AuthenticateResultModel?>.value(),
          ) as _i10.Future<_i9.AuthenticateResultModel?>);

  @override
  void logOutCurrentUser() => super.noSuchMethod(
        Invocation.method(
          #logOutCurrentUser,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<_i9.AuthenticateResultModel?> processAuthenticateResult(
    _i9.AuthenticateResultModel? authenticateResultModel,
    _i34.UserCredential? userCredential,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processAuthenticateResult,
          [
            authenticateResultModel,
            userCredential,
          ],
        ),
        returnValue: _i10.Future<_i9.AuthenticateResultModel?>.value(),
        returnValueForMissingStub:
            _i10.Future<_i9.AuthenticateResultModel?>.value(),
      ) as _i10.Future<_i9.AuthenticateResultModel?>);
}

/// A class which mocks [AuthenticationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationService extends _i1.Mock
    implements _i35.AuthenticationService {
  @override
  _i2.Logger get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
      ) as _i2.Logger);

  @override
  _i10.Future<_i36.TenantAvailableModel?> isTenantAvailable(
          {required String? tenantCode}) =>
      (super.noSuchMethod(
        Invocation.method(
          #isTenantAvailable,
          [],
          {#tenantCode: tenantCode},
        ),
        returnValue: _i10.Future<_i36.TenantAvailableModel?>.value(),
        returnValueForMissingStub:
            _i10.Future<_i36.TenantAvailableModel?>.value(),
      ) as _i10.Future<_i36.TenantAvailableModel?>);

  @override
  _i10.Future<_i9.AuthenticateResultModel?> login(
          {required _i34.UserCredential? userCredential}) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {#userCredential: userCredential},
        ),
        returnValue: _i10.Future<_i9.AuthenticateResultModel?>.value(),
        returnValueForMissingStub:
            _i10.Future<_i9.AuthenticateResultModel?>.value(),
      ) as _i10.Future<_i9.AuthenticateResultModel?>);

  @override
  _i10.Future<dynamic> processAuthenticateResult(
    _i9.AuthenticateResultModel? authenticateResultModel,
    _i34.UserCredential? userCredential,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processAuthenticateResult,
          [
            authenticateResultModel,
            userCredential,
          ],
        ),
        returnValue: _i10.Future<dynamic>.value(),
        returnValueForMissingStub: _i10.Future<dynamic>.value(),
      ) as _i10.Future<dynamic>);

  @override
  _i10.Future<bool?> register({required _i37.RegisterUser? registerUser}) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {#registerUser: registerUser},
        ),
        returnValue: _i10.Future<bool?>.value(),
        returnValueForMissingStub: _i10.Future<bool?>.value(),
      ) as _i10.Future<bool?>);

  @override
  _i10.Future<_i29.ForgotPassword?> forgotPassword(
          {required String? userNameOrEmailAddress}) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [],
          {#userNameOrEmailAddress: userNameOrEmailAddress},
        ),
        returnValue: _i10.Future<_i29.ForgotPassword?>.value(),
        returnValueForMissingStub: _i10.Future<_i29.ForgotPassword?>.value(),
      ) as _i10.Future<_i29.ForgotPassword?>);

  @override
  _i10.Future<bool?> resetForgotPassword(
          {required _i38.ResetForgotPassword? resetForgotPassword}) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetForgotPassword,
          [],
          {#resetForgotPassword: resetForgotPassword},
        ),
        returnValue: _i10.Future<bool?>.value(),
        returnValueForMissingStub: _i10.Future<bool?>.value(),
      ) as _i10.Future<bool?>);

  @override
  void logOutCurrentUser() => super.noSuchMethod(
        Invocation.method(
          #logOutCurrentUser,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<bool> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<_i28.CurrentLoginInformation?> getUserLoginInfo(
          [bool? forceUpdate = false]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserLoginInfo,
          [forceUpdate],
        ),
        returnValue: _i10.Future<_i28.CurrentLoginInformation?>.value(),
        returnValueForMissingStub:
            _i10.Future<_i28.CurrentLoginInformation?>.value(),
      ) as _i10.Future<_i28.CurrentLoginInformation?>);

  @override
  void setUserInfo() => super.noSuchMethod(
        Invocation.method(
          #setUserInfo,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.BaseResponse isPasswordCompliant(
    String? password,
    String? username, [
    int? minLength = 6,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #isPasswordCompliant,
          [
            password,
            username,
            minLength,
          ],
        ),
        returnValue: _FakeBaseResponse_6(
          this,
          Invocation.method(
            #isPasswordCompliant,
            [
              password,
              username,
              minLength,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeBaseResponse_6(
          this,
          Invocation.method(
            #isPasswordCompliant,
            [
              password,
              username,
              minLength,
            ],
          ),
        ),
      ) as _i8.BaseResponse);
}

/// A class which mocks [CmsApiManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockCmsApiManager extends _i1.Mock implements _i39.CmsApiManager {
  @override
  _i2.Logger get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
      ) as _i2.Logger);

  @override
  _i10.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  dynamic handelError(_i7.DioException? dioError) => super.noSuchMethod(
        Invocation.method(
          #handelError,
          [dioError],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<_i7.Response<dynamic>> retryInternal(
          _i7.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #retryInternal,
          [requestOptions],
        ),
        returnValue:
            _i10.Future<_i7.Response<dynamic>>.value(_FakeResponse_5<dynamic>(
          this,
          Invocation.method(
            #retryInternal,
            [requestOptions],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i7.Response<dynamic>>.value(_FakeResponse_5<dynamic>(
          this,
          Invocation.method(
            #retryInternal,
            [requestOptions],
          ),
        )),
      ) as _i10.Future<_i7.Response<dynamic>>);

  @override
  _i10.Future<dynamic> get(
    String? uri, {
    Map<String, dynamic>? queryParameters,
    _i7.Options? options,
    _i7.CancelToken? cancelToken,
    _i7.ProgressCallback? onReceiveProgress,
    bool? showLoader = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [uri],
          {
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
            #showLoader: showLoader,
          },
        ),
        returnValue: _i10.Future<dynamic>.value(),
        returnValueForMissingStub: _i10.Future<dynamic>.value(),
      ) as _i10.Future<dynamic>);

  @override
  _i10.Future<dynamic> post(
    String? uri, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i7.Options? options,
    _i7.CancelToken? cancelToken,
    _i7.ProgressCallback? onSendProgress,
    _i7.ProgressCallback? onReceiveProgress,
    bool? showLoader = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [uri],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
            #showLoader: showLoader,
          },
        ),
        returnValue: _i10.Future<dynamic>.value(),
        returnValueForMissingStub: _i10.Future<dynamic>.value(),
      ) as _i10.Future<dynamic>);
}

/// A class which mocks [CmsAccessTokenRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockCmsAccessTokenRepo extends _i1.Mock
    implements _i40.CmsAccessTokenRepo {
  @override
  _i2.Logger get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
      ) as _i2.Logger);

  @override
  _i10.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i9.AuthenticateResultModel?>
      getAccessTokenFromStorageOrRefresh() => (super.noSuchMethod(
            Invocation.method(
              #getAccessTokenFromStorageOrRefresh,
              [],
            ),
            returnValue: _i10.Future<_i9.AuthenticateResultModel?>.value(),
            returnValueForMissingStub:
                _i10.Future<_i9.AuthenticateResultModel?>.value(),
          ) as _i10.Future<_i9.AuthenticateResultModel?>);

  @override
  void logOutCurrentUser() => super.noSuchMethod(
        Invocation.method(
          #logOutCurrentUser,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<_i9.AuthenticateResultModel?> processAuthenticateResult(
    _i9.AuthenticateResultModel? authenticateResultModel,
    _i34.UserCredential? userCredential,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processAuthenticateResult,
          [
            authenticateResultModel,
            userCredential,
          ],
        ),
        returnValue: _i10.Future<_i9.AuthenticateResultModel?>.value(),
        returnValueForMissingStub:
            _i10.Future<_i9.AuthenticateResultModel?>.value(),
      ) as _i10.Future<_i9.AuthenticateResultModel?>);

  @override
  _i9.AuthenticateResultModel buildAuthenticateResultModel(
    dynamic result,
    _i34.UserCredential? userCredential,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildAuthenticateResultModel,
          [
            result,
            userCredential,
          ],
        ),
        returnValue: _FakeAuthenticateResultModel_7(
          this,
          Invocation.method(
            #buildAuthenticateResultModel,
            [
              result,
              userCredential,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeAuthenticateResultModel_7(
          this,
          Invocation.method(
            #buildAuthenticateResultModel,
            [
              result,
              userCredential,
            ],
          ),
        ),
      ) as _i9.AuthenticateResultModel);
}

/// A class which mocks [CmsAuthenticationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCmsAuthenticationService extends _i1.Mock
    implements _i41.CmsAuthenticationService {
  @override
  _i2.Logger get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
      ) as _i2.Logger);

  @override
  _i10.Future<_i9.AuthenticateResultModel?> login(
          {required _i34.UserCredential? userCredential}) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {#userCredential: userCredential},
        ),
        returnValue: _i10.Future<_i9.AuthenticateResultModel?>.value(),
        returnValueForMissingStub:
            _i10.Future<_i9.AuthenticateResultModel?>.value(),
      ) as _i10.Future<_i9.AuthenticateResultModel?>);

  @override
  _i10.Future<dynamic> processAuthenticateResult(
    _i9.AuthenticateResultModel? authenticateResultModel,
    _i34.UserCredential? userCredential,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processAuthenticateResult,
          [
            authenticateResultModel,
            userCredential,
          ],
        ),
        returnValue: _i10.Future<dynamic>.value(),
        returnValueForMissingStub: _i10.Future<dynamic>.value(),
      ) as _i10.Future<dynamic>);

  @override
  void logOutCurrentUser() => super.noSuchMethod(
        Invocation.method(
          #logOutCurrentUser,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<bool> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<_i28.CurrentLoginInformation?> getUserLoginInfo(
          [bool? forceUpdate = false]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserLoginInfo,
          [forceUpdate],
        ),
        returnValue: _i10.Future<_i28.CurrentLoginInformation?>.value(),
        returnValueForMissingStub:
            _i10.Future<_i28.CurrentLoginInformation?>.value(),
      ) as _i10.Future<_i28.CurrentLoginInformation?>);
}

/// A class which mocks [AuthSessionCoordinator].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthSessionCoordinator extends _i1.Mock
    implements _i42.AuthSessionCoordinator {
  @override
  _i2.Logger get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
      ) as _i2.Logger);

  @override
  _i10.Future<void> routeAfterStartup() => (super.noSuchMethod(
        Invocation.method(
          #routeAfterStartup,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i27.AuthPortal?> resolveStartupPortal() => (super.noSuchMethod(
        Invocation.method(
          #resolveStartupPortal,
          [],
        ),
        returnValue: _i10.Future<_i27.AuthPortal?>.value(),
        returnValueForMissingStub: _i10.Future<_i27.AuthPortal?>.value(),
      ) as _i10.Future<_i27.AuthPortal?>);

  @override
  _i10.Future<void> switchToPortal(_i27.AuthPortal? targetPortal) =>
      (super.noSuchMethod(
        Invocation.method(
          #switchToPortal,
          [targetPortal],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> logoutPortal(_i27.AuthPortal? portal) =>
      (super.noSuchMethod(
        Invocation.method(
          #logoutPortal,
          [portal],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> logoutAllPortals() => (super.noSuchMethod(
        Invocation.method(
          #logoutAllPortals,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> routeAfterPortalLogout(_i27.AuthPortal? loggedOutPortal) =>
      (super.noSuchMethod(
        Invocation.method(
          #routeAfterPortalLogout,
          [loggedOutPortal],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> routeToLogin(_i27.AuthPortal? initialPortal) =>
      (super.noSuchMethod(
        Invocation.method(
          #routeToLogin,
          [initialPortal],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> routeToPortalHome(_i27.AuthPortal? portal) =>
      (super.noSuchMethod(
        Invocation.method(
          #routeToPortalHome,
          [portal],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [ConnectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionService extends _i1.Mock implements _i43.ConnectionService {
  @override
  _i2.Logger get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
      ) as _i2.Logger);

  @override
  int get latency => (super.noSuchMethod(
        Invocation.getter(#latency),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  set latency(int? _latency) => super.noSuchMethod(
        Invocation.setter(
          #latency,
          _latency,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.StreamController<dynamic> get connectionChangeController =>
      (super.noSuchMethod(
        Invocation.getter(#connectionChangeController),
        returnValue: _FakeStreamController_8<dynamic>(
          this,
          Invocation.getter(#connectionChangeController),
        ),
        returnValueForMissingStub: _FakeStreamController_8<dynamic>(
          this,
          Invocation.getter(#connectionChangeController),
        ),
      ) as _i10.StreamController<dynamic>);

  @override
  set connectionChangeController(
          _i10.StreamController<dynamic>? _connectionChangeController) =>
      super.noSuchMethod(
        Invocation.setter(
          #connectionChangeController,
          _connectionChangeController,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasConnection => (super.noSuchMethod(
        Invocation.getter(#hasConnection),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get showConnectionStatus => (super.noSuchMethod(
        Invocation.getter(#showConnectionStatus),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#showConnectionStatus),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#showConnectionStatus),
        ),
      ) as String);

  @override
  String get showConnectivityResultDisplayName => (super.noSuchMethod(
        Invocation.getter(#showConnectivityResultDisplayName),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#showConnectivityResultDisplayName),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#showConnectivityResultDisplayName),
        ),
      ) as String);

  @override
  _i10.Stream<dynamic> get connectionChange => (super.noSuchMethod(
        Invocation.getter(#connectionChange),
        returnValue: _i10.Stream<dynamic>.empty(),
        returnValueForMissingStub: _i10.Stream<dynamic>.empty(),
      ) as _i10.Stream<dynamic>);

  @override
  String getConnectivityResultDisplayName() => (super.noSuchMethod(
        Invocation.method(
          #getConnectivityResultDisplayName,
          [],
        ),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getConnectivityResultDisplayName,
            [],
          ),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.method(
            #getConnectivityResultDisplayName,
            [],
          ),
        ),
      ) as String);

  @override
  _i10.Future<void> pingGetLatency() => (super.noSuchMethod(
        Invocation.method(
          #pingGetLatency,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i11.InternetConnectionChecker> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i10.Future<_i11.InternetConnectionChecker>.value(
            _FakeInternetConnectionChecker_9(
          this,
          Invocation.method(
            #init,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i11.InternetConnectionChecker>.value(
                _FakeInternetConnectionChecker_9(
          this,
          Invocation.method(
            #init,
            [],
          ),
        )),
      ) as _i10.Future<_i11.InternetConnectionChecker>);

  @override
  _i10.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> hasInternetInternetConnection() => (super.noSuchMethod(
        Invocation.method(
          #hasInternetInternetConnection,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
}

/// A class which mocks [WorkerQueManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkerQueManager extends _i1.Mock implements _i44.WorkerQueManager {
  @override
  _i2.Logger get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
      ) as _i2.Logger);

  @override
  bool get isExecuting => (super.noSuchMethod(
        Invocation.getter(#isExecuting),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set isExecuting(bool? _isExecuting) => super.noSuchMethod(
        Invocation.setter(
          #isExecuting,
          _isExecuting,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get maxConcurrentTasks => (super.noSuchMethod(
        Invocation.getter(#maxConcurrentTasks),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get runningTasks => (super.noSuchMethod(
        Invocation.getter(#runningTasks),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  set runningTasks(int? _runningTasks) => super.noSuchMethod(
        Invocation.setter(
          #runningTasks,
          _runningTasks,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Stream<dynamic> get onSyncTaskChange => (super.noSuchMethod(
        Invocation.getter(#onSyncTaskChange),
        returnValue: _i10.Stream<dynamic>.empty(),
        returnValueForMissingStub: _i10.Stream<dynamic>.empty(),
      ) as _i10.Stream<dynamic>);

  @override
  void initialize() => super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> enqueSingle(
    _i45.BackgroundJobInfo? value, [
    bool? startNow = true,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #enqueSingle,
          [
            value,
            startNow,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> enqueForStartUp() => (super.noSuchMethod(
        Invocation.method(
          #enqueForStartUp,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> enqueMany(List<_i45.BackgroundJobInfo>? iterable) =>
      (super.noSuchMethod(
        Invocation.method(
          #enqueMany,
          [iterable],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> startExecution({bool? forceRun = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #startExecution,
          [],
          {#forceRun: forceRun},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> delayStartQue({int? delayInSec = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #delayStartQue,
          [],
          {#delayInSec: delayInSec},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateJobValues(_i45.BackgroundJobInfo? jobInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateJobValues,
          [jobInfo],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> tryProcessJob(_i45.BackgroundJobInfo? jobInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #tryProcessJob,
          [jobInfo],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [SyncManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncManager extends _i1.Mock implements _i46.SyncManager {
  @override
  _i2.Logger get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
      ) as _i2.Logger);

  @override
  _i12.Cron get cron => (super.noSuchMethod(
        Invocation.getter(#cron),
        returnValue: _FakeCron_10(
          this,
          Invocation.getter(#cron),
        ),
        returnValueForMissingStub: _FakeCron_10(
          this,
          Invocation.getter(#cron),
        ),
      ) as _i12.Cron);

  @override
  _i12.ScheduledTask get st => (super.noSuchMethod(
        Invocation.getter(#st),
        returnValue: _FakeScheduledTask_11(
          this,
          Invocation.getter(#st),
        ),
        returnValueForMissingStub: _FakeScheduledTask_11(
          this,
          Invocation.getter(#st),
        ),
      ) as _i12.ScheduledTask);

  @override
  set st(_i12.ScheduledTask? _st) => super.noSuchMethod(
        Invocation.setter(
          #st,
          _st,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get serviceStopped => (super.noSuchMethod(
        Invocation.getter(#serviceStopped),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void start() => super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stop() => super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> startBackgroundJob() => (super.noSuchMethod(
        Invocation.method(
          #startBackgroundJob,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [FileStoreIsolateInitializer].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileStoreIsolateInitializer extends _i1.Mock
    implements _i47.FileStoreIsolateInitializer {
  @override
  _i10.Future<void> initializeFileStoreIsolate({bool? useIsolate = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #initializeFileStoreIsolate,
          [],
          {#useIsolate: useIsolate},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}
